import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic } from "next/font/google";
import "./globals.css";


import { ClerkProvider } from "@clerk/nextjs";
import ConditionalNavbar from "./componenets/ConditionalNavbar";
import ConditionalFooterAndCta from "./componenets/ConditionalFooterAndCta";

const IbmPlex = IBM_Plex_Sans_Arabic({
  subsets: ["latin"],
  weight: ["400", "700", "100", "200", "300", "500"], // Ensure the required font weights are included
  display: "swap",
});

export const metadata: Metadata = {
  title: "Aliservices",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${IbmPlex.className}  antialiased`}>
         <ConditionalNavbar />
          {children}
          {/* <Faqs faqsData={faqData} /> */}
        <ConditionalFooterAndCta/>
        </body>
      </html>
    </ClerkProvider>
  );
}
